# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '08:00'
      timezone: 'Europe/Stockholm'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
